### ISSUE TITLE
No justfile found

### ISSUE THREAD

**Issue by spuder** [Justintime50/easypost-tools-ui#74]
Attempting to follow the README to install shows the user needs to run `just setup`

`just` is installed and in the path, yet attempting to use it how the instructions show results in an error. `No justfile found`
```
 ls
CHANGELOG.md			LICENSE				docker-compose-prod.yml		docker-compose.yml
Dockerfile			README.md			docker-compose.override.yml	src
```
```just setup
error: No justfile found
```

Are the `just` instructions outdated?

**Comment by Justintime50** [comment]
Are you running it from the `src` directory? This was an unfortunate necessity in the past based on project structure though I'm looking to see if I can move the justfile to the root where it makes more sense.

**Comment by spuder** [comment]
Thanks I didn't realize I needed to be in `src` dir. 

Is php version 8.3 really required? Could it be bumped to support 8.4? 

```
just setup
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - php-vcr/php-vcr is locked to version 1.8.0 and an update of this package was not requested.
    - php-vcr/php-vcr 1.8.0 requires php ^8,<8.2|>=8.2.9,<8.4 -> your php version (8.4.1) does not satisfy that requirement.
  Problem 2
    - justintime50/vcr-accessories is locked to version v0.3.0 and an update of this package was not requested.
    - justintime50/vcr-accessories v0.3.0 requires php-vcr/php-vcr ^1.7 -> satisfiable by php-vcr/php-vcr[1.8.0].
    - php-vcr/php-vcr 1.8.0 requires php ^8,<8.2|>=8.2.9,<8.4 -> your php version (8.4.1) does not satisfy that requirement.

error: Recipe `install` failed on line 19 with exit code 2
error: Recipe `setup` failed with exit code 2
```

**Comment by Justintime50** [comment]
This project supports php 8.4; however, a downstream [testing dependency does not](https://github.com/php-vcr/php-vcr/blob/master/composer.json#L19), I apologize. For now I would stick with 8.3 until PHP VCR loosens their PHP version pinning (unlikely to be soon, they are often very slow to react).

Alternatively you could install dependencies and skip dev deps which should get you where you need to be.
